<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reviews.proto

namespace GPBMetadata;

class Reviews
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB3\x01\x0A\x0Dreviews.proto\"u\x0A\x06Review\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12)\x0A!relative_publish_time_description\x18\x02 \x01(\x09\x12\x0E\x0A\x06rating\x18\x03 \x01(\x05\x12\x0C\x0A\x04text\x18\x04 \x01(\x09\x12\x14\x0A\x0Cpublish_time\x18\x05 \x01(\x09\"#\x0A\x07Reviews\x12\x18\x0A\x07reviews\x18\x01 \x03(\x0B2\x07.Reviewb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

