<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reviews.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Reviews</code>
 */
class Reviews extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Review reviews = 1;</code>
     */
    private $reviews;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Review[] $reviews
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Reviews::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Review reviews = 1;</code>
     * @return RepeatedField<\Review>
     */
    public function getReviews()
    {
        return $this->reviews;
    }

    /**
     * Generated from protobuf field <code>repeated .Review reviews = 1;</code>
     * @param \Review[] $var
     * @return $this
     */
    public function setReviews(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Review::class);
        $this->reviews = $arr;

        return $this;
    }

}

