<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reviews.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Review</code>
 */
class Review extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string relative_publish_time_description = 2;</code>
     */
    protected $relative_publish_time_description = '';
    /**
     * Generated from protobuf field <code>int32 rating = 3;</code>
     */
    protected $rating = 0;
    /**
     * Generated from protobuf field <code>string text = 4;</code>
     */
    protected $text = '';
    /**
     * Generated from protobuf field <code>string publish_time = 5;</code>
     */
    protected $publish_time = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $relative_publish_time_description
     *     @type int $rating
     *     @type string $text
     *     @type string $publish_time
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Reviews::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string relative_publish_time_description = 2;</code>
     * @return string
     */
    public function getRelativePublishTimeDescription()
    {
        return $this->relative_publish_time_description;
    }

    /**
     * Generated from protobuf field <code>string relative_publish_time_description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRelativePublishTimeDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->relative_publish_time_description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rating = 3;</code>
     * @return int
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * Generated from protobuf field <code>int32 rating = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRating(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->rating = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 4;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setText(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string publish_time = 5;</code>
     * @return string
     */
    public function getPublishTime()
    {
        return $this->publish_time;
    }

    /**
     * Generated from protobuf field <code>string publish_time = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPublishTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->publish_time = $var;

        return $this;
    }

}

